add_newline = false

format = """\
$time$username\
[](fg:color2 bg:color4)\
$directory\
[](fg:color4 bg:color6)\
$git_branch\
$git_status\
[](fg:color6 bg:color8)\
$python\
[](fg:color8)\
$character\
"""

palette = 'colors'

[palettes.colors]
color1 = '#cbc4cf'
color2 = '#211e24'
color3 = '#d5bbfc'
color4 = '#3a255b'
color5 = '#cec2db'
color6 = '#352d40'
color7 = '#f1b7c3'
color8 = '#4b252e'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ 󱑍 $time ](fg:color1 bg:color2)'

[username]
format = '[$user ](fg:color1 bg:color2)'

[directory]
format = "[ $path ](fg:color3 bg:color4)"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ](fg:color5 bg:color6)'
symbol = "  "

[git_status]
format = '[$all_status ](fg:color5 bg:color6)'

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)"
added_style = "fg:color5 bg:color6"
deleted_style = "fg:color5 bg:color6"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]"
symbol = " "

[python]
# Show python version and virtual environment name
python_binary = ["python3", "python"]
format = "[ (${virtualenv}) ](fg:color7 bg:color8)"

[character]
success_symbol = '[ ](color1 bold)'
error_symbol = '[ ✗](#ffb4ab bold)'

[cmd_duration]
min_time = 5000
format = "[ 󱑍 $duration ](fg:color1 bg:color2)"
