add_newline = false

format = """\
$time\
$username\
[](fg:#816D5F bg:#D9B154)\
$directory\
[](fg:#D9B154 bg:#FCC440)\
$git_branch\
$git_status\
[](fg:#FCC440 bg:#88786D)\
$python\
[](fg:#88786D)\
$character\
"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ 󱑍 $time ]($style)'
style = "fg:#322D29 bg:#816D5F"

[directory]
format = "[ $path ]($style)"
style = "fg:#322D29 bg:#D9B154"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#322D29 bg:#FCC440"

[git_status]
format = '[$all_status ]($style)'
style = "fg:#322D29 bg:#FCC440"

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)"
added_style = "fg:#322D29 bg:#FCC440"
deleted_style = "fg:#322D29 bg:#FCC440"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ 󱑍 $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[](bold green)'
error_symbol = '[ ✗]()'

[username]
format = '[$user ]($style)'
style_root = "fg:#FFF3EB bg:#816D5F"

[python]
# Show python version and virtual environment name
python_binary = ["python3", "python"]
format = "[ (${virtualenv}) ]($style)"
style = "fg:#322D29 bg:#88786D"
