add_newline = false

format = """\
$time\
$username\
[](fg:#363a4f bg:#b7bdf8)\
$directory\
[](fg:#b7bdf8 bg:#c6a0f6)\
$git_branch\
$git_status\
[](fg:#c6a0f6 bg:#8aadf4)\
$python\
[](fg:#8aadf4)\
$character\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#24273a bg:#b7bdf8"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#24273a bg:#c6a0f6"

[git_status]
format = '[$all_status ]($style)'
style = "fg:#24273a bg:#c6a0f6"

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)"
added_style = "fg:#24273a bg:#c6a0f6"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ 󱑍 $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[](bold green)'
error_symbol = '[ ✗](#ed8796)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ 󱑍 $time ]($style)'
style = "fg:#b7bdf8 bg:#363a4f"

[username]
format = '[$user ]($style)'
style_root = "fg:#b7bdf8 bg:#363a4f"

[python]
# Show python version and virtual environment name
python_binary = ["python3", "python"]
format = "[ (${virtualenv}) ]($style)"
style = "fg:#24273a bg:#8aadf4"
