return {
  "RedsXDD/neopywal.nvim",
  enabled = true,
  name = "neopywal",
  lazy = false,
  priority = 1000,
  opts = {},
  config = function()
    require("neopywal").setup({
      use_wallust = true,
      transparent_background = true,
      plugins = {
        alpha = true,
        dashboard = false,
        git_gutter = true,
        indent_blankline = true,
        lazy = true,
        lazygit = true,
        noice = false,
        notify = true,
        nvim_cmp = true,
        mason = true,
        mini = {
          hipatterns = true,
          indentscope = {
            enabled = true,
          },
          pick = true,
          starter = true,
        },
        telescope = {
          enabled = true,
          -- style = "nvchad"
        },
      },
      fileformats = {
        c_cpp = true,
        c_sharp = true,
        clojure = false,
        cmake = true,
        common_lisp = false,
        css = true,
        dart = false,
        diff = true,
        elixir = false,
        erlang = false,
        git_commit = true,
        go = true,
        haskell = false,
        help = true,
        html = true,
        ini = false,
        java = false,
        javascript = true,
        javascript_react = false,
        json = true,
        kotlin = false,
        latex = false,
        less = false,
        lua = true,
        makefile = true,
        markdown = true,
        matlab = false,
        objectivec = false,
        ocaml = false,
        perl = false,
        php = true,
        powershell = false,
        python = true,
        restructuredtext = false,
        ruby = false,
        rust = true,
        sass = false,
        scala = false,
        shell = true,
        swift = false,
        toml = true,
        typescript = true,
        viml = true,
        xml = false,
        yaml = true,
        zsh = true,
      },
    })
    vim.cmd.colorscheme("neopywal")
  end,
}
