return {
  -- {
  --   "nvim-tree/nvim-tree.lua",
  --   lazy = false,
  --   dependencies = {
  --     "nvim-tree/nvim-web-devicons",
  --   },
  --   opts = {
  --     hijack_cursor = true,
  --     disable_netrw = true,
  --     --   -- window = {
  --     --   --   mappings = {
  --     --   --     ["\\"] = "close_window",
  --     --   --   },
  --     --   -- },
  --   },
  --
  --   config = function()
  --     require("nvim-tree").setup({
  --       sort = {
  --         sorter = "case_sensitive",
  --       },
  --       view = {
  --         width = 30,
  --       },
  --       renderer = {
  --         group_empty = true,
  --       },
  --       filters = {
  --         -- dotfiles = true,
  --         custom = {
  --           "^.git$",
  --         },
  --       },
  --     })
  --     local api = require("nvim-tree.api")
  --     api.events.subscribe(api.events.Event.FileCreated, function(file)
  --       vim.cmd("edit " .. vim.fn.fnameescape(file.fname))
  --     end)
  --   end,
  -- },
  -- {
  --   "nvim-neo-tree/neo-tree.nvim",
  --   version = "*",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
  --     "MunifTanjim/nui.nvim",
  --   },
  --   cmd = "Neotree",
  --   keys = {
  --     { "\\", ":Neotree reveal<CR>", desc = "NeoTree reveal", silent = true },
  --   },
  --   opts = {
  --     filesystem = {
  --       window = {
  --         mappings = {
  --           ["\\"] = "close_window",
  --         },
  --       },
  --       filtered_items = {
  --         visible = true, -- This is what you want: If you set this to `true`, all "hide" just mean "dimmed out"
  --         hide_dotfiles = false,
  --         hide_gitignored = true,
  --       },
  --     },
  --   },
  -- }
}
